### ISSUE TITLE
trainee screen missing field and add API to change trainee status

### ISSUE THREAD

**Issue by khsnh** [sechmachine727/fms-backend-api#134]
- [x] ~~Missing status field in get all trainees~~ List trainee status in list groups when viewing trainee detail
- [x] Add API to change status of trainees added to a group (refer to how fams is changing status of trainees)
- [x] Change status in Group Trainee from uppercase to normal like other screens

**Comment by sechmachine727** [comment]
ke

**Comment by sechmachine727** [comment]
@khsnh implement the checked items in front end
