### ISSUE TITLE
150 test case for UT

### ISSUE THREAD

**Issue by PhamTuanDuongs** [sechmachine727/fms-backend-api#189]
- [x] `FmsClassServiceImplTest` : 85TC 86% Branch Coverage

- [x] `TrainingProgramServiceImplTest` : 30TC 100% Branch coverage

- [x] `TrainingCalendarServiceImplTest` : 38TC 96% Branch coverage

Updated:

- [ ] `ClassServiceImplTest` : 96TC 98% Branch Coverage (Test class renamed)

**Comment by sechmachine727** [comment]
@DatHoang89 ali add them TC. dung git diff xem co nhung TC nao duoc them vao
